;; -*- mode: emacs-lisp; coding: utf-8-unix -*-
;; Minibuffer history file, automatically generated by ‘savehist’.

(setq savehist-minibuffer-history-variables '(file-name-history extended-command-history command-history))
(setq file-name-history '("~/repos/emacs.d/.emacs.d/isac-emacs-modules/isac-emacs-completion.el"))
(setq extended-command-history '("dired-create-empty-file" "sunrise-sunset" "display-fill-column-indicator-mode" "display-time-mode" "customize-themes"))
(setq command-history '((switch-to-buffer "isac-emacs-completion.el" nil 'force-same-window) (switch-to-buffer "init.el" nil 'force-same-window) (dired-create-empty-file "~/repos/emacs.d/.emacs.d/isac-emacs-modules/isac-emacs-completion.el") (execute-extended-command nil "dired-create-empty-file" "dired-create-em") (sunrise-sunset 1) (execute-extended-command nil "sunrise-sunset" "sun") (display-fill-column-indicator-mode 'toggle) (execute-extended-command nil "display-fill-column-indicator-mode" "display-fil") (display-time-mode 'toggle) (execute-extended-command nil "display-time-mode" "display-time-mode") (display-time-mode 'toggle) (execute-extended-command nil "display-time-mode" "display-time-mode") (customize-themes) (execute-extended-command nil "customize-themes" "customize-themes")))
